"""Shared patient-context schema and canonical mappings."""
from __future__ import annotations

PATIENT_CONTEXT_FIELDS = {
    "age",
    "age_months",
    "weight_kg",
    "pregnant",
    "pregnancy_month",
    "breastfeeding",
    "conditions",
    "allergies",
    "current_medications",
    "conditions_confirmed",
    "allergies_confirmed",
    "current_medications_confirmed",
    "pregnancy_breastfeeding_confirmed",
}

CONDITION_CANONICAL = {
    "huyết áp": "hypertension",
    "cao huyết áp": "hypertension",
    "huyet ap": "hypertension",
    "cao huyet ap": "hypertension",
    "tang huyet ap": "hypertension",
    "benh cao huyet ap": "hypertension",
    "tiểu đường": "diabetes",
    "đái tháo đường": "diabetes",
    "tieu duong": "diabetes",
    "dai thao duong": "diabetes",
    "duong huyet": "diabetes",
    "tieu duong type 1": "diabetes",
    "tieu duong type 2": "diabetes",
    "bệnh tim": "heart_disease",
    "tim mạch": "heart_disease",
    "benh tim": "heart_disease",
    "tim mach": "heart_disease",
    "benh tim mach": "heart_disease",
    "suy tim": "heart_disease",
    "mach vanh": "heart_disease",
    "suy gan": "liver_disease",
    "bệnh gan": "liver_disease",
    "benh gan": "liver_disease",
    "viem gan": "liver_disease",
    "xo gan": "liver_disease",
    "suy thận": "kidney_disease",
    "bệnh thận": "kidney_disease",
    "suy than": "kidney_disease",
    "benh than": "kidney_disease",
    "than yeu": "kidney_disease",
    "suy than man": "kidney_disease",
    "dạ dày": "stomach_ulcer",
    "loét dạ dày": "stomach_ulcer",
    "da day": "stomach_ulcer",
    "bao tu": "stomach_ulcer",
    "dau bao tu": "stomach_ulcer",
    "loet da day": "stomach_ulcer",
    "viem loet da day": "stomach_ulcer",
    "viem da day": "stomach_ulcer",
    "hen": "asthma",
    "suyễn": "asthma",
    "suyen": "asthma",
    "hen suyen": "asthma",
    "hen phe quan": "asthma",
}
